//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden üretildiğinde kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiteBlog.admin
{


    public partial class adminpanel
    {
    }
}
